### ISSUE TITLE
No default min value on rep(1)sep

### ISSUE THREAD

**Issue by martijnhoekstra** [typelevel/cats-parse#111]
Repsep is 0 or more and rep1sep is 1 or more, but you still have to pass in a minimum, which feels unnatural, especially for repsep where the minimum is implied to be 0 anyway. Default values of 0 or 1, or overloads to the same effect would be useful.

**Comment by johnynek** [comment]
I'd happily take an overload. I'm not as huge of a fan with defaults as they can present some compatibility problems on changes.

Can you send a PR with a test that it behaves like expected?

The reason btw we don't force min is that originally I didn't have the Accumulator (which is a restricted version of CanBuildFrom since we always know a parser doesn't build a collection from another and generally does not know the size). But I thought this method would be used when you wanted zero or more OR you wanted the return type to be a List.

Now we have the repAs methods which allow you to control the return type (although we didn't yet make a repSepAs variant).

Lastly I'll add that we don't have a version that optionally allows a trailing separator, that might also be nice to have.

**Comment by johnynek** [comment]
@martijnhoekstra should we add a variant with only the sep?

**Comment by martijnhoekstra** [comment]
Yeah, I think so, though I'm not too sure about the other variation with trailing separator. Shall I do it?
