### ISSUE TITLE
Add a fluent API for repeating with various options.

### ISSUE THREAD

**Issue by martijnhoekstra** [typelevel/cats-parse#128]
There are various ways to repeat stuff. With or without a separator, with a minimum number of repetitions, allowing 0 repetitions or not, gathering into some accumulator. There is also a ticket open to add a maximum: https://github.com/typelevel/cats-parse/issues/97

That gives rise to a lot of different combinations for repeating parser constructors, with opportunity for inconsistency and not having some specific combinations of concerns.

What do you think about adding a fluent API starting from rep or rep0, and then adding combinators for min, max, separator and accumulator?

**Comment by johnynek** [comment]
I'm open to this but I'm a bit worried about making rep or rep0 harder to use in the default case. Like, what is the return type?

We could imagine a few possibilities:

1. a new subclass of Parser/Parser0 like RepParser/RepParser0 that has some methods that that Parser does not (like, withMin, withMax, withSep, or something like that).
2. an independent class that you have to convert at the end to a parser: .toParser or something
3. an independent class for which there is an implicit conversion to Parser

I'm a bit negative on magic APIs. A principle I like a lot is "no weird shit" (of course, what is weird is left to the reviewer, but we should put a real penalty on anything cute or fancy).

All this having been said, my bias is towards regular methods on Parser/Parser0 or the companion object. To me, a method on the companion with all the possible arguments, but defaults given, and calling with by name parameters seems good enough: it is familiar, nothing to learn, no magic, the only thing is possibly lacks is convenience in a pipeline of operations (so you might have to do: `val foo = ....; val bar = Parser.repWith(min = ... max = ... sep = ..., acc = Accumulator....)`

**Comment by martijnhoekstra** [comment]
I'll draft something with both variations.

**Comment by martijnhoekstra** [comment]
https://github.com/typelevel/cats-parse/compare/main...martijnhoekstra:rep?expand=1 is WIP on a Repeater API

I tried to abstract over Parser0 and Parser so that the min combinator works with/without allowing 0. That's probably not a fruitful direction -- the difficulty lies in the variance on the element type in the accumulator.

I'll make another one for repWith, though that might come tomorrow.

**Comment by johnynek** [comment]
One suggestion after looking at that PR: do you want to send a separate PR for a maximum number of repeats, and separate the idea of the API considerations from the capabilities?

Secondly, a suggestion: rather than using -1 as infinite, we could put max - 1 as the parameter. Then we could do `while (cnt <= maxMinusOne)`

So, if we set that to Int.MaxValue, it is always true and we recover the previous behavior (and only one comparison)

**Comment by martijnhoekstra** [comment]
That's a good idea for the sentinel.

Submitting a PR making Rep and Rep0 capable of max first so you can separate those concerns sounds good to me.

**Comment by johnynek** [comment]
So we have #132 merged.

We don't have a fluent API still. I wonder a bit if repetition is important enough to have such an API. The core repetition primitive does have an internal representation because it has a loop in it, and doing that explicitly seems to improve performance and stack safety (vs using Defer which could also be used to power recursion).

An alternative idea would be to add another series of `rep` methods that accept a `sep: Parser[Any]`.

This isn't as pretty a builder, but it does side-step what the return type should be of a partially built fluent API.

**Comment by johnynek** [comment]
#141 and #142 added all the methods we want without a fluent API, but I think it may be good enough.

**Comment by martijnhoekstra** [comment]
Let's call it good then.
