### ISSUE TITLE
publish 0.3.0

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats-parse#137]
There is conceivably one last item to consider: #128 

Any others?

cc @regadas @martijnhoekstra

**Comment by regadas** [comment]
iirc there were some ideas for additional combinators floating around, but I guess those can easily go on the next one.

For this one how are we with scalafix rules? it would be good if we could have them here in the repo. 
@martijnhoekstra did you start working on them? I can help out if you want.

**Comment by martijnhoekstra** [comment]
The scalafix is ready to go. I'll give it another testrun on http4s.

I agree it's kind of weird to have them in my repo, rather than here, but also not really a big deal. Scalafix assumes `master` for the main branch if you use a `github:` scheme, so if we do it here, we need to use the raw path rather than a git path.

**Comment by martijnhoekstra** [comment]
Other than that sounds good to me to release 0.3.0

**Comment by martijnhoekstra** [comment]
Looking at the results in http4s, I still want to make two changes to the scalafix to make it catch more:

* Also rename methods that were imported rather than selected from the Parser object. in the current version P.char1(foo) gets replaced with P.char(foo), but import P.char1; char1(foo) remains unchanged. This pattern is heavily used in http4s
* Insert a pair of parentheses when translating from `Parser.rep1(foo)` to `(foo).rep` if foo is some expression that is not just a name. In practice, foo is often `x *> y`, and we want to get `(x *> y).rep`, not `x *> y.rep`

**Comment by martijnhoekstra** [comment]
It's probably better to release now rip the Parser/Parser0 bandaid off as soon as possible. #128 needs to experiment and iterate a bit first, and I don't think it's worth holding a release up over.

As an example for the scalafix, https://github.com/http4s/http4s/compare/dotty...martijnhoekstra:rescaffoldFix?expand=1 has two commits, one with what the scalafix did, and one with the manual cleanup pass over it.

**Comment by regadas** [comment]
Oh nice! Awesome to see that there are some initial rules. Having them on the repo would probably just facilitate contribution/awareness but not concerned if they are not.

I'm +1 on getting it out now.

**Comment by martijnhoekstra** [comment]
This is where the rules are at atm @regadas  https://github.com/martijnhoekstra/catsparsescalafix/

**Comment by johnynek** [comment]
okay, do you all think we are ready to tag 0.3.0?

**Comment by johnynek** [comment]
maybe we should do #111 before we publish or close it. We have done so much rep/repSep related work on this version.

**Comment by johnynek** [comment]
okay, I guess I'll tag 0.3.0 on Monday morning to give us the weekend to see if there are any issues that pop up.

**Comment by regadas** [comment]
Sounds good!

**Comment by rossabaker** [comment]
Glad to see there's a scalafix, and even more glad to see @martijnhoekstra running them on http4s!  Some of our contributors have been nervous about the churn that's coming, so hopefully this calms some nerves.  Note that `series/0.22` is the branch to try it on if http4s is a testbed.

**Comment by martijnhoekstra** [comment]
@rossabaker I have a PR ready to go with the final changes, but it felt weird to open it before 0.3.0 is actually out.

**Comment by johnynek** [comment]
okay, tagging 0.3.0

**Comment by johnynek** [comment]
https://github.com/typelevel/cats-parse/releases/tag/v0.3.0

**Comment by johnynek** [comment]
seems to have published: https://github.com/typelevel/cats-parse/actions/runs/478850192

here is the release: https://github.com/typelevel/cats-parse/releases/tag/v0.3.0

**Comment by johnynek** [comment]
here is an example of the manual changes I needed to make after scala fix:

https://github.com/johnynek/bosatsu/pull/649/commits/eb4453d0a333f6609250f7e08e84bbcf48267fe0

pretty minor IMO.
