### ISSUE TITLE
Native Scala YAML parser

### ISSUE THREAD

**Issue by abitrolly** [typelevel/cats-parse#176]
Is it possible to work with YAML files using this library? So far all solutions I found for Scala are using Java libs for that.

See https://github.com/scala-native/scala-native/issues/2174

**Comment by johnynek** [comment]
Parsing the full yaml is notoriously hard. This is a parser combinator library that helps you write parsers, but there are few parsers (see the Number object that does some parsers... we would accept PRs for more examples).

What I have heard is that all the yaml parsing libraries are basically line-by-line ports of the original ruby parser since it is so complex with so many corner cases.

Re-open if you have more questions or comments.

**Comment by abitrolly** [comment]
@johnynek I agree that full YAML specification is a bit insane, but maybe a limited demo parser with indented input suitable for YAML subsets that could be immediately useful for the projects like like Kaitai Struct (https://github.com/kaitai-io/kaitai_struct/issues/519#issuecomment-699689785) ?

**Comment by abitrolly** [comment]
JFYI, I can't reopen issues.
