### ISSUE TITLE
Why does order matter for `|` (`orElse`), even if I use `.backtrack`?

### ISSUE THREAD

**Issue by nikololiahim** [typelevel/cats-parse#270]
I have the following example which parses a Java-like parameter list:
```scala
import cats.parse.{Parser0, Parser => P}


case class Parameter(id: String, `type`: String)

case class Parameters(params: List[Parameter], vararg: Option[Parameter])

lazy val wsp: Parser0[Unit] = P.char(' ').rep0.void
lazy val identifier: P[String] =
  P.ignoreCaseCharIn('A' to 'Z').rep.map(_.toList.mkString)
lazy val `type` = identifier
lazy val param: P[Parameter] = (
  (`type` <* wsp) ~ identifier
  ).map {
  case (typeId, id) => Parameter(id, typeId)
}
lazy val paramSep = P.char(',').surroundedBy(wsp)
lazy val withVararg: P[Parameters] = (param.repSep(1, paramSep) <* P.string("..."))
  .map(params => Parameters(params.init, Some(params.last)))

lazy val noVararg: Parser0[Parameters] = param.repSep0(paramSep).map(Parameters(_, None))
lazy val params = (
  P.char('(') *>
    (
      withVararg.backtrack | noVararg
      )
    <* P.char(')')
  )

println(params.parseAll("(typeA a, typeB b)"))
println(params.parseAll("(typeA a, typeB b...)"))
println(params.parseAll("(typeC c...)"))
println(params.parseAll("()"))
```

It does recognize the given examples correctly:
```scala
Right(Parameters(List(Parameter(a,typeA), Parameter(b,typeB)),None))
Right(Parameters(List(Parameter(a,typeA)),Some(Parameter(b,typeB))))
Right(Parameters(List(),Some(Parameter(c,typeC))))
Right(Parameters(List(),None))
```

However, when I swap `withVararg` and `noVararg` in `params` definition:
```scala
lazy val params = (
  P.char('(') *>
    (
      noVararg.backtrack | withVararg
      )
    <* P.char(')')
  )

```

I get the following result:
```scala
Right(Parameters(List(Parameter(a,typeA), Parameter(b,typeB)),None))
Left(Error(17,NonEmptyList(InRange(17,),)))))
Left(Error(8,NonEmptyList(InRange(8,),)))))
Right(Parameters(List(),None))
```

I expected it to backtrack just like in the first case, however, this doesn't seem to work this way. Can you explain why it doesn't backtrack in the second case? Also, is there a way to parse this particular example more succinctly then what I have in that big piece of code in the beginning?

I have very similar example written in Fastparse and it behaves very similarly.

**Comment by johnynek** [comment]
Yes, `|` which is the same as `orElse` is not commutative. What is happening here is that noVararg succeeds parsing for instance `typeB b...` and it succeeds parsing `typeB b` and then the next bit is `...`. Now, you exit the `noVararg.backtrack | withVararg` because you have successfully parsed up to `typeB b`. Next, the parser expects to parse `)`, but you don't find that, instead you find `...` and there is no backtrack here.

A better way to parse things like this is to parse
```scala

(noVararg ~ string("...").void.?).map { case (prefix, opt) => if (opt.isDefined) /* you have varargs */ else /* you don't */ 
```
This is a good example of potential exponential complexity in parsers. If you use backtrack every time you see this prefix, you have two possibilities, but if you avoid backtracking as I suggest above, there is never any rewinding of the state.

I hope that helps.

**Comment by nikololiahim** [comment]
Ok, so `noVararg` consumes `typeB b`, sees `.` as its next char, decides "I can't do this anymore", wraps up `noVararg` and proceeds to parsing `)`, which is not there. 

Yeah, I tried your suggestion and the problem is that it lets `(...)` through, which ends up calling `.init` on an empty list, which leads to a runtime exception.

**Comment by johnynek** [comment]
Okay, to solve that, you do:
```scala
val zeroArgs = Parser.pure(Nil)
val oneOrMoreArgs = (arg ~ dotDotDot.?).rep1sep(spaceCommaSpace).map(_.toList)
(openParens.with1 *> (oneOrMoreArgs | zeroArgs)) <* closeParens
```

**Comment by nikololiahim** [comment]
Okay, now this allows multiple varargs `(typeA a..., typeB b...)`. Sorry for being picky -_-.

**Comment by johnynek** [comment]
Are you asking for me to write a correct solution, or giving you some guidance as to why it isn't working and hints for approaches? I was assuming the latter.

If you would like me to write the code, I can probably find time to do so, but I can't do it at the moment. It might be a few days.

**Comment by nikololiahim** [comment]
Yeah, my bad, I think I know what to do from now. Thank you for instant feedback!

**Comment by nikololiahim** [comment]
Just a quick question: is it ok to write Parsers as `lazy val`s? Is it any better than just `val` or `def`?

**Comment by johnynek** [comment]
I saw a question in my email, but not here if `lazy val` is okay or `val` or `def` should be prefered.

I would say that since Parsers are immutable it doesn't matter too much, but in general I would only use `lazy val` in scala when you half to (it can cause deadlocks if you over use it). I would use it pretty much exclusively for recursive parsers, but even then I would probably use the `Parser.recursive` method instead.

**Comment by nikololiahim** [comment]
@johnynek Once again, many thanks for being so responsive! I am currently writing a parser for a small programming language and cats-parse definitely seems like a good tradeoff in terms of composability and performance. Keep up the good work!
