### ISSUE TITLE
orElse not working as expected

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [typelevel/cats-parse#311]
Given these parser.

```scala
val negativeSign = charIn('-')
val integerPart0 = (negativeSign.? ~ charIn('0')).string
val integerPart1 = (negativeSign.? ~ nonZeroDigit ~ digit.rep).string
val integerPart  = integerPart0 | integerPart1
val intValue     = integerPart
```

And the following tests.

```scala
assert(clue(integerPart.parse("-0")) == Right("", "-0"))
assert(clue(integerPart.parse("-1338")) == Right("", "-1338"))
```

The first test passes as expected. The second however fails because the parser returns this:

```scala
Left(
    value = Error(
      failedAtOffset = 1,
      expected = NonEmptyList(
        head = InRange(
          offset = 1,
          lower = '0',
          upper = '0'
        ),
        tail = Nil
      )
    )
  )
```

It's as if the `orElse` method is not moving on to the second parser (integerPart1).

**Comment by nikololiahim** [comment]
This happens because `orElse` does not backtrack by default.
Both `integerPart0` and `integerPart1` start with `negativeSign.?`. The parsers sequenced with `orElse` are tried left-to-right. So, when parsing `"-1338"`, `integerPart0` is tried first. Then, `negativeSign.?` parses successfully, __consuming the minus__. The next parser, `charIn('0')` fails, and, since `integerPart0` consumed some input (the minus), it produces an arresting failure.
In order to avoid this behaviour, you either need to restructure your parser (which is possible in this particular case), or use `.backtrack`, like this:
```scala
val integerPart  = integerPart0.backtrack | integerPart1
```
With backtrack, all the arresting failures of `integerPart0` are converted to "epsilon" failures, which enables the parser to try the next alternative, `integerPart1`, which should parse successfully.

**Comment by PaperPlaneSoftware** [comment]
@nikololiahim That is incredibly helpful, thanks so much for explaining that 👍

**Comment by johnynek** [comment]
Just a note: https://github.com/typelevel/cats-parse/blob/main/core/shared/src/main/scala/cats/parse/Numbers.scala

You can see some examples there with minimal backtracking.

Backtracking can cause exponential parsing time so if you can write the parser to avoid it (and you usually can) it is less likely to have that exponential blowup.
