### ISSUE TITLE
identifier parser

### ISSUE THREAD

**Issue by hartmut27** [typelevel/cats-parse#392]
very pretty library, thank You Creators! looking forward to dig more into it.

the small parser below works, 
but I wonder if there is a shorter version for it:
```
val identifier: Parser[String] = {
      (alpha ~ (alpha | digit | Parser.charIn('_')).rep0)
        .map { case (x, xs) => (x :: xs).mkString }
    }
```
(semantics: "identifier starting with alpha character, subsequently also numbers and underlines are allowed")

**Comment by johnynek** [comment]
I would probably write it as:

```scala
val identifier: Parser[String] =
  (alpha ~ (alpha | digit | Parser.charIn('_')).rep0).string
```

the `.string` combinator captures the literal string matched, which is what you want here rather than building an intermediate list and then converting back to `String`.

Note: This *won't* work if the `Parser[Char]` does some translating (e.g. decoding escaping, since `.string` would give you the original escaped code).  For that use case, you can use `repAs[String]` to build the string up from the `Char` values emitted from the parser (i.e. after decoding in my hypothetical example).

Thank you for taking the time to make a nice comment!

**Comment by hartmut27** [comment]
thank You :)
