### ISSUE TITLE
Recursion with `Parser0`

### ISSUE THREAD

**Issue by keirlawson** [typelevel/cats-parse#529]
I'd like to write a recursive parser that is able to handle empty strings as well as populated ones, so far as I can see this is not presently supported?

**Comment by johnynek** [comment]
it is possible, it just doesn't have quite as nice of an API since it is dangerous and risks running forever.

```scala
import cats.Defer

Defer[Parser0].fix[A] { rec: Parser0[A] =>
  // do something but make 100% sure that you only use rec in the case that you have already consumed input
}
```

If you recurse before you have consumed any input, you can just keep doing that and it won't terminate.

Usually, you don't really want this. You write a recursive parser for the non-empty case and then combine that with the empty, like `recursiveNonEmpty | handleEmptyCase`
