### ISSUE TITLE
Consistency of return types

### ISSUE THREAD

**Issue by rossabaker** [typelevel/cats-parse#64]
Spun off from an [http4s issue](https://github.com/http4s/http4s/pull/3855#discussion_r522666228).

* `char` returns a `Parser1[Unit]`. We know what it captured, so we don't return it.
* `charIn` returns a `Parser1[Char]`. It captured one of a set of characters, and we want to know which.
* `ignoreChar` returns a `Parser1[Unit]`. Arguably like `charIn` in that we don't know what it cpatured, but the docs tell us to call `.string` if we need the result.
* `string1` returns a `Parser[Unit]`.  Seems consistent with `.char`.

Did we get this right, or should everything return what it captured?

**Comment by johnynek** [comment]
A few notes:

1. Returning the captured String from string is free. We don't have to allocate (we know what we expect already).
2. Returning the string in ignoreCase is not free, we need to allocate a substring if we are capturing. If we aren't capturing there is an additional Boolean check we don't have now, probably not a big deal.
3. Returning the Char in char is cheap since we have the char, there is likely a boxing of the char but I assume the JVM has a cache of those so we are hitting a lookup table that might even be in the CPU cache.

To summarize, I doubt this is a perfect question to add the return values and since we have using `*>` and void as recommended style I guess it doesn't do much harm either.

On the other hand, matching a constant string and wanting that exact thing back is rare IME. Usually you combine it a bit more then capture a larger block with string or you use .as to change it. So I haven't felt the need.

I think we are consistent now (except arguably the ignoreCase variants maybe should return what they capture), so I think the discussion would be helped if we had some examples where one did want to capture directly the results of these parsers.

**Comment by rossabaker** [comment]
As I get deeper into this, I'm feeling more comfortable with the way it is.  A mild discomfort: in the spirit of "return Unit if constant, return the value when variable", this rule from RFC5234 should return a `Char`. To do so would require a couple annoying `.as`es, because it's composed of two Unit rules.

```
  val wsp: Parser1[Unit] =
    sp.orElse1(htab)
```

I made a judgment call that which kind of whitespace is found is generally uninteresting, and left it as `Unit`.
